server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: M0TT0fr33!@#
    url: jdbc:mysql://localhost:3306/sundaland
    username: root
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true