server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: rootroot
    url: jdbc:mysql://teamoneofficialdatabase.c4eqo06kg56i.us-east-1.rds.amazonaws.com/sundaland
    username: admin
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

